### ISSUE TITLE
Special Question Mark Block After "..." with Chinese Characters

### ISSUE THREAD

**Issue by stepbystepcode** [llanosrocas/yaziline.yazi#2]
https://github.com/llanosrocas/yaziline.yazi/blob/73f6cddc67da80551333e192c33c77dfdcf0f30a/init.lua#L65
![telegram-cloud-photo-size-5-6293954004975206590-y](https://github.com/user-attachments/assets/92f1cefe-9b42-455a-b04b-7a7c812d22fc)

# Description
I’ve encountered a display issue in the Yaziline plugin for Yazi where filenames containing Chinese characters are not rendering correctly. Specifically, after the "..." (ellipsis) in filenames, a special question mark block (�) appears. This issue only occurs with Chinese characters and does not happen with English characters. I am using the JetBrainsMonoNL Nerd Font Mono font, which works correctly in other applications, so this is not a font-related issue.

# Steps to Reproduce:

Open Yazi with the Yaziline plugin enabled.

Navigate to a directory where filenames contain Chinese characters (e.g., "AI赛题环境部署文档.pdf").

Observe the display of filenames in the terminal.

# Expected Behavior:
Filenames should display correctly without any special question mark blocks after the ellipsis.

# Actual Behavior:
Two special question mark block (��) appears after the "..." in filenames containing Chinese characters.

# Environment:

OS: macOS Sequoia 15.1 arm64

Terminal: iTerm2

Font: JetBrainsMonoNL Nerd Font Mono

Yazi Version: Yazi 0.4.1 (Homebrew 2024-12-10)

Yaziline Plugin Version: 2.2.3

Additional Information:

The issue only occurs with Chinese characters; English filenames display correctly.

I’ve tested this in multiple terminal emulators, and the problem persists.

Screenshots or logs can be provided if needed.

# Possible Causes:

The issue might be related to how Yaziline handles Unicode characters, particularly Chinese characters, during ellipsis truncation.

There could be a mismatch in character encoding or rendering logic for non-ASCII characters.

# Suggested Fix:

Investigate the rendering logic for filenames in the Yaziline plugin, especially around ellipsis truncation and Chinese character handling.

Ensure proper Unicode support and compatibility with non-ASCII characters.

Thank you for your attention to this issue! Let me know if you need further details or assistance in debugging.

Best regards,
stepbystepcode

**Comment by llanosrocas** [comment]
Hello.
Can you please send me a filename (or filenames) in Chinese as a string?

**Comment by stepbystepcode** [comment]
AI赛题环境部署文档.pdf

**Comment by stepbystepcode** [comment]
![image](https://github.com/user-attachments/assets/11c10a76-3b9d-40fc-a456-3db6d4376c67)

**Comment by llanosrocas** [comment]
I just pushed the fixed version. Please try it.
I also found a bug with the truncate length, so with the new logic, you might want to update your config to something like this:

```lua
filename_max_length = 9,
filename_truncate_length = 4
```
<img width="358" alt="Screenshot 2024-12-29 at 15 14 12" src="https://github.com/user-attachments/assets/2698257e-15cd-411d-b741-21f7c7d47860" />

**Comment by stepbystepcode** [comment]
It works, thank you! 🥰
